### ISSUE TITLE
Add support for custom Parsers of Markdown metadata/attributes (for YAML, Joplin, etc); Make the current Elixir Map parser one of the parser options

### ISSUE THREAD

**Issue by alfredbaudisch** [alfredbaudisch/pardall_markdown#30]
Make it similar to [dashbitco/nimble_publisher#16](https://github.com/dashbitco/nimble_publisher/pull/16) (thank you [@dkuku](https://github.com/dkuku)).

---

Original issue was focused on a single new parser for YAML:
For better compatibility with posts from other static website builders. 

- https://jekyllrb.com/docs/front-matter/
- Parser: https://github.com/KamilLelonek/yaml-elixir

**Comment by dkuku** [comment]
I've recently pushed a pr to nimble publisher to have an option for custom parser-do you think this can be done in a way thats compatible between the packages as a hex dependency? 
https://github.com/dashbitco/nimble_publisher/pull/16

**Comment by alfredbaudisch** [comment]
I liked your idea, having it as a hex dependency can be useful.

**Comment by dkuku** [comment]
The Code.eval_string trick may be good if you keep the data inside your app as nimble publisher does. But when you want to allow parsing external folders possibly modified by others it's a security threat.

**Comment by alfredbaudisch** [comment]
> I've recently pushed a pr to nimble publisher to have an option for custom parser-do you think this can be done in a way thats compatible between the packages as a hex dependency?
> [dashbitco/nimble_publisher#16](https://github.com/dashbitco/nimble_publisher/pull/16)

@dkuku implemented as per your idea, thank you.
