### ISSUE TITLE
Author/Write pages from the deployed app itself

### ISSUE THREAD

**Issue by gbrls** [alfredbaudisch/pardall_markdown#60]
I like writing at medium.com because it's very easy to write and publish, but it has many disadvantages. `PardallMarkdown` looks very good and with the LiveView functionality I believe it'd be possible to have a very streamlined _write and publish_ workflow.

It'd need some sort of authentication and authorization for a user to log-in and start writing and messing with the server's filesystem.
I'm willing to work on this in my free time, this tool really fits my expectations, I'd like to know your opinions about this feature. 

### Example use case

- I'm taking classes at my Uni and can just open any computer in the lab, log-in to my page and take notes there.

**Comment by alfredbaudisch** [comment]
Hey @gbrls, this is completely doable with PardallMarkdown, as a matter of fact, it's the perfect use-case. For example, right now, the sample project https://pardall.xyz/ via https://github.com/alfredbaudisch/pardall-markdown-phoenix-demo, gets articles published via Markdown files pushed from a watched Git repo.

You could start with that as a base, then you add the CRUD interface to create and edit the Markdown content within the Phoenix application itself. You could start with Phoenix's default LiveView or even HTML CRUDs and expand upon that (Phoenix even has an auth generator built-in).
